import React, { useState, useEffect } from "react";
import {
  Box, Card, CardContent, Typography, Button, Grid, Chip,
  Alert, CircularProgress, Divider, List, ListItem, ListItemText,
  LinearProgress,
} from "@mui/material";
import PsychologyIcon from "@mui/icons-material/Psychology";
import BoltIcon from "@mui/icons-material/Bolt";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";

const API = import.meta.env.VITE_API_URL || "http://localhost:5001/api";
const C = { primary: "#0F766E", secondary: "#06B6D4" };

export default function SmartPlan({ token, userId, dayContext, onClearDay }) {
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Auto-generate when a day is passed in from Study Planner
  useEffect(() => {
    if (dayContext) generateForDay(dayContext);
  }, [dayContext]);

  const generateForDay = async (ctx) => {
    setLoading(true);
    setError("");
    setPlan(null);
    try {
      const topicNames = ctx.topics.map(t => t.name).join(", ");
      const res = await fetch(`${API}/resources/smartplan`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          day: ctx.day,
          topics: ctx.topics,
          subject: ctx.subject,
          hours: ctx.hours,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to generate smart plan");
      setPlan({ ...data, dayContext: ctx });
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box>
      {/* Header */}
      <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 3 }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
          <PsychologyIcon sx={{ fontSize: 36, color: C.primary }} />
          <Box>
            <Typography variant="h5" sx={{ fontWeight: 700, color: C.primary }}>
              Smart Plan
            </Typography>
            <Typography variant="caption" color="textSecondary">
              Gemini AI generates a detailed hour-by-hour study strategy for your day
            </Typography>
          </Box>
        </Box>
        {onClearDay && plan && (
          <Button variant="outlined" size="small" onClick={onClearDay}
            sx={{ borderColor: C.primary, color: C.primary, borderRadius: 2 }}>
            ← Back to Study Planner
          </Button>
        )}
      </Box>

      {/* No context state */}
      {!dayContext && !plan && !loading && (
        <Card sx={{ borderRadius: 3, border: "2px dashed #CBD5E1", textAlign: "center" }}>
          <CardContent sx={{ py: 6 }}>
            <Typography variant="h2" sx={{ mb: 2 }}>🧠</Typography>
            <Typography variant="h6" sx={{ fontWeight: 600, color: "#64748B", mb: 1 }}>
              No Day Selected
            </Typography>
            <Typography variant="body2" color="textSecondary">
              Go to Study Planner, generate a plan, then click the
              <strong> "🧠 Smart Plan"</strong> button on any day card to get a detailed AI study strategy.
            </Typography>
          </CardContent>
        </Card>
      )}

      {/* Loading */}
      {loading && (
        <Card sx={{ borderRadius: 3, border: "1px solid #E2E8F0", textAlign: "center" }}>
          <CardContent sx={{ py: 6 }}>
            <CircularProgress sx={{ color: C.primary, mb: 2 }} />
            <Typography variant="h6" sx={{ fontWeight: 600, color: C.primary }}>
              🤖 Gemini is building your smart plan...
            </Typography>
            <Typography variant="body2" color="textSecondary" sx={{ mt: 1 }}>
              Analyzing topics and creating an optimized hour-by-hour schedule
            </Typography>
          </CardContent>
        </Card>
      )}

      {error && <Alert severity="error" sx={{ mb: 3, borderRadius: 2 }}>{error}</Alert>}

      {/* Plan result */}
      {plan && !loading && (
        <>
          <Alert severity="success" sx={{ mb: 3, borderRadius: 2 }}>
            ✨ Smart plan generated by Gemini AI for Day {plan.dayContext?.day} — {plan.dayContext?.subject}
          </Alert>

          {/* Day summary */}
          <Grid container spacing={2} sx={{ mb: 3 }}>
            {[
              { label: "Day", value: `Day ${plan.dayContext?.day}`, color: C.primary },
              { label: "Subject", value: plan.dayContext?.subject || "—", color: C.secondary },
              { label: "Topics", value: plan.dayContext?.topics?.length || 0, color: "#8B5CF6" },
              { label: "Hours", value: `${plan.dayContext?.hours}h`, color: "#F59E0B" },
            ].map(s => (
              <Grid item xs={6} sm={3} key={s.label}>
                <Card sx={{ borderRadius: 3, textAlign: "center", border: `2px solid ${s.color}30` }}>
                  <CardContent sx={{ py: 1.5 }}>
                    <Typography variant="h6" sx={{ fontWeight: 700, color: s.color }}>{s.value}</Typography>
                    <Typography variant="caption" color="textSecondary">{s.label}</Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>

          {/* Overview */}
          {plan.overview && (
            <Card sx={{ mb: 3, borderRadius: 3, background: "#F0F9FF", border: "1px solid #BAE6FD" }}>
              <CardContent>
                <Typography variant="subtitle2" sx={{ fontWeight: 700, color: C.primary, mb: 1 }}>
                  📋 Study Strategy Overview
                </Typography>
                <Typography variant="body2" color="textSecondary">{plan.overview}</Typography>
              </CardContent>
            </Card>
          )}

          {/* Hour-by-hour schedule */}
          {plan.schedule && plan.schedule.length > 0 && (
            <Card sx={{ mb: 3, borderRadius: 3, border: "1px solid #E2E8F0" }}>
              <CardContent>
                <Typography variant="h6" sx={{ fontWeight: 700, color: C.primary, mb: 2 }}>
                  ⏰ Hour-by-Hour Schedule
                </Typography>
                <List sx={{ p: 0 }}>
                  {plan.schedule.map((slot, i) => (
                    <ListItem key={i} sx={{
                      py: 1.5, borderBottom: "1px solid #F1F5F9",
                      "&:last-child": { borderBottom: "none" },
                      alignItems: "flex-start",
                    }}>
                      <Box sx={{ minWidth: 80, mr: 2 }}>
                        <Chip label={slot.time} size="small"
                          sx={{ background: `${C.primary}15`, color: C.primary, fontWeight: 700, fontSize: "0.7rem" }} />
                      </Box>
                      <Box sx={{ flex: 1 }}>
                        <Typography variant="body2" sx={{ fontWeight: 600, color: "#1E293B", mb: 0.5 }}>
                          {slot.activity}
                        </Typography>
                        {slot.tip && (
                          <Typography variant="caption" color="textSecondary">
                            💡 {slot.tip}
                          </Typography>
                        )}
                      </Box>
                      {slot.type && (
                        <Chip label={slot.type} size="small"
                          sx={{
                            background: slot.type === "break" ? "#FEF3C7" : slot.type === "revision" ? "#EFF6FF" : "#D1FAE5",
                            color: slot.type === "break" ? "#92400E" : slot.type === "revision" ? "#1D4ED8" : "#065F46",
                            fontSize: "0.65rem", fontWeight: 600,
                          }} />
                      )}
                    </ListItem>
                  ))}
                </List>
              </CardContent>
            </Card>
          )}

          {/* Topic breakdown */}
          {plan.topicBreakdown && plan.topicBreakdown.length > 0 && (
            <Card sx={{ mb: 3, borderRadius: 3, border: "1px solid #E2E8F0" }}>
              <CardContent>
                <Typography variant="h6" sx={{ fontWeight: 700, color: C.primary, mb: 2 }}>
                  📚 Topic Breakdown
                </Typography>
                <Grid container spacing={2}>
                  {plan.topicBreakdown.map((t, i) => (
                    <Grid item xs={12} sm={6} key={i}>
                      <Box sx={{ p: 2, background: "#F8FAFC", borderRadius: 2, border: "1px solid #E2E8F0" }}>
                        <Typography variant="body2" sx={{ fontWeight: 700, color: "#1E293B", mb: 0.5 }}>
                          {t.topic}
                        </Typography>
                        <Box sx={{ display: "flex", gap: 1, mb: 1, flexWrap: "wrap" }}>
                          <Chip label={`${t.duration} mins`} size="small" sx={{ background: "#EFF6FF", color: C.primary, fontSize: "0.65rem" }} />
                          <Chip label={t.approach} size="small" sx={{ background: "#D1FAE5", color: "#065F46", fontSize: "0.65rem" }} />
                        </Box>
                        {t.resources && (
                          <Typography variant="caption" color="textSecondary">{t.resources}</Typography>
                        )}
                      </Box>
                    </Grid>
                  ))}
                </Grid>
              </CardContent>
            </Card>
          )}

          {/* Tips */}
          {plan.tips && plan.tips.length > 0 && (
            <Card sx={{ borderRadius: 3, background: "#FFFBEB", border: "1px solid #FDE68A" }}>
              <CardContent>
                <Typography variant="subtitle2" sx={{ fontWeight: 700, color: "#92400E", mb: 1.5 }}>
                  ⚡ Pro Tips for Today
                </Typography>
                {plan.tips.map((tip, i) => (
                  <Box key={i} sx={{ display: "flex", gap: 1, mb: 1 }}>
                    <CheckCircleIcon sx={{ color: "#F59E0B", fontSize: 18, mt: 0.2, flexShrink: 0 }} />
                    <Typography variant="body2" color="textSecondary">{tip}</Typography>
                  </Box>
                ))}
              </CardContent>
            </Card>
          )}
        </>
      )}
    </Box>
  );
}
